### ISSUE TITLE
CLI name clash

### ISSUE THREAD

**Issue by DavidMStraub** [dvandyk/syncrm#7]
My Ubuntu has a remote magnetic tape server rmt:
https://www.systutorials.com/docs/linux/man/1-rmt/

To avoid a name clash I suggest renaming the executable. I can submit a PR, but I can't decide about the name...

**Comment by dvandyk** [comment]
Yes, I have seen that on my workstation today as well. Let's brain storm a name over lunch?

**Comment by dvandyk** [comment]
Lunch proposals were:
 - ```sync-rm```;
 - ```rm-sync```, with the obvious problem of being lexicographically close to ```rm```;
 - ```rm-tool```

I think I prefer ```sync-rm```.

**Comment by DavidMStraub** [comment]
`syncrm`?

**Comment by dvandyk** [comment]
Even better.

**Comment by DavidMStraub** [comment]
So what should be changed?

Name of 
- [x] executable
- [x] Python module
- [x] PyPI package
- [x] Github repo

**Comment by dvandyk** [comment]
All of the above! Be consistent.
