### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by DavidMStraub** [dvandyk/syncrm#9]
- [ ]  `librsvg2-bin` is required; this should be added to the README
- [ ] `pdftk` is required. This is more of an issue since this was removed from the Ubuntu package repositories in 18.04 LTS since it depends on GCJ that is no longer maintained.

**Comment by DavidMStraub** [comment]
Maybe there are pure Python solutions for both problems, e.g. (not having looked at them in detail)

- https://cairosvg.org/
- https://pypi.org/project/pyPdf/

**Comment by dvandyk** [comment]
The ```pdftk``` issue is a real bummer. But from a cursory glance it appears like ```pyPdf``` is an option to replace it.

**Comment by mseri** [comment]
Dropping support to `pdftk` using a pure python solution is doable, you can check the code at: https://github.com/reHackable/maxio/pull/22

I am using `pyPDF2` there, but you can do the same also with `pdfrw` (also purely python).

With very long documents you notice the difference between using `pdftk` or relying on a pure python implementation, but nothing unbearable (I think the slowest I've got was around 2 minutes)

**Comment by dvandyk** [comment]
Fixed in the master branch thanks to David!
